### ISSUE TITLE
adding covariates

### ISSUE THREAD

**Issue by jackhump** [qqwang-berkeley/JUM#17]
Hi, this package looks like fun. I have 3 datasets where the same biological condition is compared to a set of controls. I was hoping to analyse the 3 datasets jointly adding a covariate for dataset. Is it possible to pass this to DEXSeq via the support file? So with DEXSeq I'd fit:

```
formulaFullModel = ~ sample + exon + dataset:exon + condition:exon
formulaReducedModel = ~ sample + exon + dataset:exon
```

What do you suggest?

**Comment by qqwang-berkeley** [comment]
Hi Jack,

I just want to make sure that I understand your request correctly. Do you
mean that you want to run JUM in a way that analyzes three datasets from
one biological condition jointly? Or do you mean you want to run DEXSeq
instead?

Qingqing

**Comment by jackhump** [comment]
Sorry Qingqing, I wasn't clear.
I was under the impression that JUM uses DEXSeq for the downstream statistical testing for differential junction usage? 
If so, could I run JUM on all 3 datasets together to find a joint set of splicing events and then run the statistical testing part with a dataset-specific covariate?

**Comment by qqwang-berkeley** [comment]
Hi Jack,

In step 2 (the Rscript step in the manual) JUM does utilize functions from
the DEXSeq package to calculate differential junction usage in each AS
structure. This step is then followed by two JUM-unique steps (JUM_B.sh and
JUM_C.sh) that reconstitute the tissue-specific AS graph *ab initio*,
assign splicing patterns for each AS event, perform rigorous intron
retention analysis, and calculate deltaPSI values.

If you have your own preference for running the statistical testing step,
you can modify the R_script_JUM.R so that it fits your needs. Take a look
at the R script. It should be straightforward. Let me know if you have any
questions.

Qingqing
