### ISSUE TITLE
Perl Error due to a sample not having AS on one contig

### ISSUE THREAD

**Issue by rLannes** [qqwang-berkeley/JUM#44]
Hi!

I encounter the following Error Running JUM_A:
ERROR: Database file output_long_intron_sorted.gff contains chromosome X_3, but the query file does not.
       Please rerun with the -g option for a genome file.
       See documentation for details.

the following command shows results for all except one sample.
grep X_3   control_vs_Treat/*Aligned.out.sorted.bed

I believe the error come from the process_sortedbam() function
During the intersection steps!

May be a way to resolve this issue is to extract from all sample the @SQ tag and merge them to build a bed genome.txt file.
and then give this genome to the bedtools intersect inside process_sortedbam.

Could you help me? my perl is very bad....

**Comment by qqwang-berkeley** [comment]
This is really weird. If the samples are processed properly you should not see this error. Did you make sure that the process_sortedbam() function ran successfully on every sample? Sometimes due to the memory limit certain sample processing steps were terminated in the backstage without notifying you. If you want, I can share with you a modified version of JUM that perform sample processing sequentially but not in parallel so that you can be sure every sample is pre-processed properly.

**Comment by rLannes** [comment]
Hi, thank you for your answer.
That was the error, I increased the memory available and the error disappeared.
I should have closed the issue, sorry for that
